# Generated by Django 6.1 on 2026-08-29 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0012_organization_alter_financialmetric_month_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReconciliationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_processed', models.IntegerField()),
                ('matched', models.IntegerField()),
                ('exceptions_count', models.IntegerField()),
                ('match_rate_pct', models.FloatField()),
                ('accuracy_overall_f1', models.FloatField(blank=True, null=True)),
                ('processing_time_ms', models.IntegerField()),
                ('ai_summary', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agents.organization')),
            ],
        ),
        migrations.CreateModel(
            name='ReconciliationException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txn_id', models.CharField(max_length=100)),
                ('exception_type', models.CharField(max_length=100)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('settlement_amount', models.FloatField(blank=True, null=True)),
                ('ledger_amount', models.FloatField(blank=True, null=True)),
                ('delta', models.FloatField(blank=True, null=True)),
                ('ai_reasoning', models.TextField(blank=True)),
                ('ground_truth_type', models.CharField(blank=True, max_length=100)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='agents.reconciliationrun')),
            ],
        ),
    ]
