# Generated by Django 6.1 on 2026-08-29 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0015_reconciliationexception_classification_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='reconciliationexception',
            name='ledger_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='reconciliationexception',
            name='settlement_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
