# Generated by Django 6.0.7 on 2026-08-08 08:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0012_organization_alter_financialmetric_month_and_more'),
        ('echo', '0002_conversation_organization_memoryfact_embedding_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='conversation',
            name='echo_conver_user_id_4eb679_idx',
        ),
        migrations.AddField(
            model_name='conversation',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='specialist',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['user', 'archived_at', '-last_active_at'], name='echo_conver_user_id_32e651_idx'),
        ),
    ]
